language: java
git:
  depth: 3
deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  file: processed.zip
  skip_cleanup: true
  on:
    tags: true
matrix:
  include:
  - os: linux
    script:
    - ./gradlew assemble
    - ./gradlew check --info
    - rm .gitignore
    - chmod +x make.sh
    - ./make.sh
    - zip -r processed{.zip,} > nul

