language: java
git:
  depth: 3
matrix:
  include:
  - os: linux
    script:
    - ./gradlew assemble
    - ./gradlew check --info
    - rm .gitignore
    - chmod +x make.sh
    #- cat make.sh
    - ./make.sh
    #- git add processed/
    #- git commit -m .

