language: java
git:
  depth: 3
matrix:
  include:
  - os: linux
    script:
    - ./gradlew assemble
    - ./gradlew check --info
    - rm .gitignore
    - git status
    - ./make.sh
    - git add processed/
    - git commit -m .

