language: java
git:
  depth: 3
deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  file: processed.zip
  skip_cleanup: true
  on:
    tags: true
matrix:
  include:
  - os: linux
    script:
    - wget https://github.com/jomof/nihonpipe/releases/download/0.0.6/processed.zip > nul 2>nul
    - unzip processed.zip > nul 2>nul
    - ./gradlew assemble
    - ./gradlew check --info
    - chmod +x make.sh
    - ./make.sh
    - zip -r processed{.zip,} > nul

